<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_username</name>
   <tag></tag>
   <elementGuidId>db5dedd1-2336-46c7-89ee-d0917f61ed31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[@name='username']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer.username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
