<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_addres</name>
   <tag></tag>
   <elementGuidId>801b5207-42f9-4f55-845f-33b60551a284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//input[@id='customer.address.street']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer.address.street']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
