<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_password</name>
   <tag></tag>
   <elementGuidId>3204c7bc-a60c-427f-b6fc-14079e4e645c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[@name='username']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer.password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
