<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_firstname</name>
   <tag></tag>
   <elementGuidId>fc3eb90b-cdf0-43b6-bcfd-5a5926e77d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//input[@id='customer.firstName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
